name: Test on ubuntu
on: 
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run lint

  format-check: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run format:check

